### ISSUE TITLE
Add a link to the Snowflake extension

### ISSUE THREAD

**Issue by WofWca** [glenn-sorrentino/relaylove#3]
**Is your feature request related to a problem? Please describe.**
Having a tab always open is a bit of a headache.

**Describe the solution you'd like**
Add a link to where the users can install the extension (e.g. https://chrome.google.com/webstore/detail/snowflake/mafpmfcccpbjnhfhjnllmmalhifmlcie)

**Describe alternatives you've considered**
At least a link to https://snowflake.torproject.org

**Additional context**
![image](https://user-images.githubusercontent.com/39462442/210770730-d841c205-ae46-47cb-9388-7b4b34a410db.png)

**Comment by glenn-sorrentino** [comment]
Great suggestion. I've added the links and they're live on the site now! 

<img width="856" alt="Screenshot 2023-01-05 at 10 00 38 AM" src="https://user-images.githubusercontent.com/28545431/210848938-e105028a-a090-43a6-9984-acd65ac4a65a.png">
